export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const LOAD_SECTIONS_SUCCESS = "LOAD_SECTIONS_SUCCESS";

export const LOAD_UNITS_SUCCESS = "LOAD_UNITS_SUCCESS";

export const LOAD_CART_SUCCESS = "LOAD_CART_SUCCESS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const UPDATE_PRODUCT_IN_CART_LOCALLY_SUCCESS =
  "UPDATE_PRODUCT_IN_CART_LOCALLY_SUCCESS";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const DELETE_PRODUCT_FROM_CART_SUCCESS =
  "DELETE_PRODUCT_FROM_CART_SUCCESS";

export const LOAD_STORES_SUCCESS = "LOAD_STORES_SUCCESS";
export const LOAD_STORE_BY_URL_FRIENDLY_NAME_SUCCESS =
  "LOAD_STORE_BY_URL_FRIENDLY_NAME_SUCCESS";

export const LOAD_STORE_SECTIONS_BY_STORE_URL_FRIENDLY_NAME_SUCCESS =
  "LOAD_STORE_SECTIONS_BY_STORE_URL_FRIENDLY_NAME_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const AUTHENTICATE = "AUTHENTICATE";
